(()=>{
const I=n=>`<svg class="i"><use href="#${n}"/></svg>`,C=(t,p,k='')=>`<div class="flow-card ${k}"><h3>${t}</h3><p>${p}</p></div>`,R=(i,t,s,a='›')=>`<div class="flow-row"><div class="flow-icon">${I(i)}</div><div class="flow-main"><b>${t}</b><small>${s}</small></div><span class="flow-action">${a}</span></div>`,B=(t,g)=>`<button class="flow-btn" data-go="${g||''}">${t}</button>`;
const screens=[
['splash','Splash','Brand trust and fast loading.',null,`<div class="splash"><div class="brandmark">B</div><h2>TheBrokrs</h2><p>Brokering trust in every rupee</p><small style="margin-top:90px;opacity:.6">Securely loading…</small></div>`],
['onboard1','Onboarding · Value','The complete value proposition.',null,`<div class="art"><div class="orb">${I('trend')}</div></div><span class="flow-badge">1 of 4</span><h2 class="screen-title">Smarter everyday decisions, all in one place.</h2><p class="screen-sub">Invest, protect your family, access healthcare and earn useful rewards.</p><div class="pager"><i class="on"></i><i></i><i></i><i></i></div>${B('Continue','onboard2')}`],
['onboard2','Onboarding · Trust','Security in plain language.',null,`<div class="art" style="background:linear-gradient(145deg,#ffe79b,#ffad74)"><div class="orb">${I('shield')}</div></div><span class="flow-badge">2 of 4</span><h2 class="screen-title">Verified partners. Transparent choices.</h2><p class="screen-sub">Clear terms, secure consent and visible benefits at every step.</p><div class="pager"><i></i><i class="on"></i><i></i><i></i></div>${B('Continue','onboard3')}`],
['onboard3','Onboarding · Rewards','Rewards with real utility.',null,`<div class="art" style="background:linear-gradient(145deg,#ddd4ff,#927fff)"><div class="orb">${I('gift')}</div></div><span class="flow-badge">3 of 4</span><h2 class="screen-title">Earn points for actions that matter.</h2><p class="screen-sub">Referrals, healthy habits and milestones become useful rewards.</p><div class="pager"><i></i><i></i><i class="on"></i><i></i></div>${B('Continue','onboard4')}`],
['onboard4','Onboarding · Family','Multi-person account utility.',null,`<div class="art"><div class="orb">${I('users')}</div></div><span class="flow-badge">4 of 4</span><h2 class="screen-title">Built for you and your family.</h2><p class="screen-sub">Secure benefits, documents and reminders in one place.</p><div class="pager"><i></i><i></i><i></i><i class="on"></i></div>${B('Get started','phone')}`],
['phone','Phone sign in','Phone-first Indian authentication.',null,`<span class="flow-badge">Secure sign in</span><h2 class="screen-title">Welcome to TheBrokrs</h2><p class="screen-sub">Enter your mobile number to continue.</p><div class="field"><label>Mobile number</label><b>🇮🇳 +91 &nbsp; 98765 43210</b></div>${B('Send secure OTP','otp')}<button class="flow-btn secondary">Continue with Google</button>${C('🎁 Welcome reward','100 points after sign in + 200 after completing KYC.','tint')}<p style="font-size:8px;text-align:center;color:var(--muted)">By continuing, you agree to the Terms and Privacy Policy.</p>`],
['otp','OTP verification','Auto-read, resend and voice fallback.',null,`<span class="flow-badge">One-time password</span><h2 class="screen-title">Check your messages</h2><p class="screen-sub">Sent to +91 98••• ••210 · <b>Change</b></p><div class="otp"><span>4</span><span>7</span><span>2</span><span>8</span><span>1</span><span>6</span></div>${B('Verify & continue','setup')}<button class="flow-btn secondary">Use voice OTP</button><p style="text-align:center;font-size:9px">Resend in 00:42</p>`],
['setup','Profile setup','Light personalization before home.',null,`<span class="flow-badge">Almost there</span><h2 class="screen-title">Tell us about you</h2><div class="field"><label>Full name</label><b>Rohit Sharma</b></div><div class="metric-grid"><div class="field"><label>Date of birth</label><b>12 May 1992</b></div><div class="field"><label>City</label><b>Hyderabad</b></div></div><div class="chips" style="flex-wrap:wrap"><span class="chip active">Investments</span><span class="chip">Health</span><span class="chip active">Farming</span><span class="chip">Insurance</span></div>${C('Permissions are your choice','Location and WhatsApp can be changed anytime.')}${B('Create my profile','home')}`],
['insights','Your week','Cross-service activity timeline.','home',`${C('Portfolio value','<b style="font-size:22px;color:#18221d">₹4,82,150</b> · <span style="color:#0b7b53">+1.8%</span>','tint')}<div class="metric-grid"><div class="metric"><small>Investments</small><b>₹3.2L</b></div><div class="metric"><small>Farm assets</small><b>₹1.1L</b></div></div>${R('heart','Dr. Mehta · 11:30 AM','Video consultation · Today')}${R('shield','Policy renewal','₹4,820 · In 12 days')}${R('trend','Monthly SIP','₹5,000 · In 3 days')}`],
['referrals','Refer & earn','Transparent referral loop.','rewards',`${C('Your referral code','<b style="font-size:24px;color:#18221d">ROHIT50</b>','tint')}${B('Share invite link')}<div class="metric-grid"><div class="metric"><small>Invited</small><b>12</b></div><div class="metric"><small>Signed up</small><b>7</b></div><div class="metric"><small>First action</small><b>4</b></div><div class="metric"><small>Earned</small><b>1,600</b></div></div>`],
['tiers','Tiers & perks','Lifetime status and benefits.','rewards',`${C('Current tier · Gold','2,840 lifetime points · 7,160 to Platinum','dark')}${R('star','Bronze','0+ pts · Base earn','✓')}${R('star','Silver','2,500+ pts · +5%','✓')}${R('star','Gold · You','10,000+ pts · Priority support','NOW')}${R('star','Platinum','50,000+ pts · Concierge','LOCKED')}`],
['ledger','Points ledger','Auditable earning and spending.','rewards',`${C('Available balance','<b style="font-size:22px;color:#18221d">2,840 pts</b>')}${R('tag','Bikanervala bill','Partner spend · 2h ago','+21')}${R('users','Anil invested','Referral vested','+500')}${R('gift','Dining coupon','Redeemed yesterday','−500')}${R('star','Daily streak','12 days','+50')}`],
['redeem','Redeem points','Useful rewards with clear caps.','rewards',`${R('tag','₹250 shopping voucher','2,000 pts · Instant','Redeem')}${R('heart','Free video consultation','800 pts · Once/month','Redeem')}${R('leaf','₹500 farm top-up','5,000 pts · Quarterly','Redeem')}${R('heart','Donate to GiveIndia','Any amount','Donate')}`],
['offer-detail','Bikanervala','Verified partner offer.','offers',`<div class="offer-hero"><small>GOLD EXCLUSIVE</small><h3>Flat 20% off your bill</h3><p>Minimum ₹300 · Save up to ₹150</p></div>${C('Earn 2× points on Wednesdays','Gold members earn 2 pts for every ₹20.','tint')}${B('Activate offer','activate')}<button class="flow-btn secondary">Save for later</button>${R('building','Nearby outlets','142 verified locations')}`],
['activate','Offer activated','Secure code and bill verification.','offers',`${C('Bikanervala · Banjara Hills','Valid for 14:32 minutes','dark')}<div style="width:140px;height:140px;margin:16px auto;background:repeating-linear-gradient(45deg,#18221d 0 6px,#fff 6px 12px);border:12px solid white"></div><p style="text-align:center;font-weight:900">BK • 84H2</p>${C('How it works','Show the code, pay, then upload the bill for points.')}${B('I paid · Upload bill')}`],
['coupons','My coupons','Active, used and expired offers.','offers',`${R('tag','Bikanervala · 20%','Expires in 2 days','Use')}${R('heart','Tata 1mg · 15%','Health checkups','Use')}${R('plane','MakeMyTrip · ₹500','Expires 30 Sep','Use')}${C('💡 Double your savings','Combine eligible coupons with card offers.','tint')}`],
['farms','Specialty farming','Two curated, insured farm products.','search',`${C('Why specialty farms?','High-value crops, controlled cultivation and transparent project updates.','tint')}<div class="farm-product saffron-card" data-go="farm-detail"><span class="product-label">PREMIUM CROP</span><b>Saffron Cultivation</b><small>Pampore, Kashmir · Controlled beds</small><div><strong>13.8% target IRR</strong><em>58% funded</em></div></div><div class="farm-product mushroom-card" data-go="mushroom-detail"><span class="product-label">SHORT CYCLE</span><b>Mushroom Farming</b><small>Pune, Maharashtra · Climate-controlled units</small><div><strong>11.6% target IRR</strong><em>72% funded</em></div></div>${C('Built for transparency','Track cultivation, quality checks, insurance and projected payouts.')}`],
['farm-detail','Saffron Cultivation','Premium crop project details.','search',`<div class="photo saffron-hero"><span><small>PAMPORE · KASHMIR</small><b>Saffron grown in controlled indoor beds</b></span></div><div class="metric-grid"><div class="metric"><small>Target IRR</small><b>13.8%</b></div><div class="metric"><small>Tenure</small><b>12 mo</b></div><div class="metric"><small>Minimum</small><b>₹10,000</b></div><div class="metric"><small>Risk</small><b>Moderate</b></div></div>${C('Expert-led cultivation','GI-region corm sourcing, controlled irrigation, batch testing and crop insurance.')}${R('leaf','Current stage','Corm preparation · On schedule','Live')}${B('Choose saffron units','esign')}`],
['mushroom-detail','Mushroom Farming','Short-cycle controlled farming.','search',`<div class="photo mushroom-hero"><span><small>PUNE · MAHARASHTRA</small><b>Climate-controlled gourmet mushroom units</b></span></div><div class="metric-grid"><div class="metric"><small>Target IRR</small><b>11.6%</b></div><div class="metric"><small>Tenure</small><b>8 mo</b></div><div class="metric"><small>Minimum</small><b>₹5,000</b></div><div class="metric"><small>Risk</small><b>Low–Moderate</b></div></div>${C('Repeatable harvest cycles','Temperature monitoring, verified off-take partners and contamination cover.')}${R('leaf','Current stage','Growing-room preparation','Live')}${B('Choose mushroom units','esign')}`],
['farm-live','Saffron Project · Live','Post-investment cultivation tracking.','home',`${C('Projected value','<b style="font-size:22px;color:#18221d">₹11,380</b> · +13.8%','tint')}${R('leaf','Cultivation log · Week 8','Corm sprouting is healthy','2d')}${R('shield','Quality & insurance','Batch cover active','7d')}${R('doc','Field report','Agronomist verified','12d')}`],
['invest','Investments','Portfolio and product discovery.','search',`${C('Portfolio value','<b style="font-size:22px;color:#18221d">₹3,21,540</b> · +1.8%','tint')}${R('trend','Axis Bluechip','SIP ₹5,000 · ₹1.37L','+14.2%')}${R('trend','Parag Parikh Flexi Cap','SIP ₹3,000 · ₹86k','+22.6%')}${B('Explore mutual funds')}`],
['insurance','Insurance','Compare, renew and claim.','search',`${C('Health · HDFC Ergo','₹5L cover · Renews in 12 days')}${R('shield','HDFC Ergo Optima','₹8,200/year','Best')}${R('shield','Care Supreme','₹9,180/year','Compare')}${R('shield','Star Health','₹7,920/year','Lowest')}${B('Compare 5 plans')}`],
['health','Healthcare','Hospitals, doctors and records.','search',`${C('Emergency help','Nearest cashless hospital and assisted calling.')}${R('heart','Apollo · Banjara Hills','4.7 ★ · 2.4 km','Book')}${R('heart','Medicover','4.5 ★ · ₹300 OPD','Book')}${R('doc','Family health locker','12 records · ABHA-ready','Open')}`],
['it','IT services','Fixed price and escrow delivery.','search',`${R('brief','Starter website','5 pages · 14 days','₹9,999')}${R('brief','Mobile application','Flutter · 30 days','₹49,999')}${R('building','Cloud + AMC','24×7 support','₹4,999/mo')}${B('Share custom requirement')}`],
['esign','Review & eSign','Consent before payment.','search',`<div class="metric-grid"><div class="metric"><small>Investment</small><b>₹10,000</b></div><div class="metric"><small>Projected yield</small><b>₹1,240</b></div></div>${R('doc','SPV agreement','12 pages · Digio verified','Review')}${R('shield','KYC requirement','PAN + Aadhaar ready','✓')}${C('Your consent matters','Review risks and payout schedule before signing.')}${B('eSign & continue','payment')}`],
['payment','Secure payment','UPI-first checkout.','search',`${C('Amount payable','<b style="font-size:23px;color:#18221d">₹10,000</b>')}${R('plane','UPI · rohit@oksbi','Default · Instant','✓')}${R('tag','HDFC Debit · •••• 4421','Secure card payment','Select')}${R('building','Net banking','All major banks','Select')}${B('Pay securely · ₹10,000','success')}`],
['success','Investment confirmed','Completion and reward feedback.','home',`<div style="width:80px;height:80px;border-radius:50%;background:#d8f56c;color:#0b7b53;display:grid;place-items:center;margin:20px auto;font-size:35px">✓</div><h2 class="screen-title" style="text-align:center">Your farm units are confirmed.</h2><p class="screen-sub" style="text-align:center">₹10,000 invested securely in your selected specialty farm.</p>${C('+1,000 reward points','Gold 2× multiplier included.','tint')}${B('Track live project','farm-live')}<button class="flow-btn secondary" data-go="home">Back home</button>`],
['inbox','Inbox','Unified cross-service alerts.','profile',`${R('leaf','Saffron project · Week 8','Healthy corm sprouting','2h')}${R('gift','Anil invested','+500 pts vesting','5h')}${R('heart','Dr. Mehta · 11:30','Video link ready','Today')}${R('shield','Policy renewal','Due in 12 days','1d')}`],
['kyc','KYC & limits','Profile-owned verification.','profile',`${R('user','Phone verified','Ending 210','Done')}${R('doc','PAN verified','Investments and tax','Done')}${R('shield','Aadhaar eKYC','Tokenized · Never stored','Done')}${R('user','Video verification','High-value actions','Start')}${C('Your data, your control','Review or withdraw consent in Privacy & Security.','tint')}`],
['family','Family members','Shared utility with individual consent.','profile',`${R('user','Rohit Sharma','Primary · Verified','You')}${R('user','Sneha Sharma','Spouse · Health linked','Manage')}${R('user','Aarav Sharma','Child · Health linked','Manage')}${R('users','Add family member','Invite securely','Add')}`],
['documents','Documents','Secure family locker.','profile',`${R('doc','Identity documents','PAN · Aadhaar token','Open')}${R('heart','Health records','12 files · ABHA-ready','Open')}${R('trend','Investment statements','CAS · Tax reports','Open')}${R('shield','Insurance policies','3 active files','Open')}`],
['security','Privacy & security','Consent and device controls.','profile',`${R('shield','App lock','Biometric enabled','On')}${R('user','Two-factor auth','OTP + trusted device','On')}${R('doc','Consent manager','7 active consents','Review')}${R('brief','Logged-in devices','2 trusted','Manage')}`],
['preferences','Notifications','Channel and frequency controls.','profile',`${R('bell','Account activity','Push + SMS','On')}${R('trend','Investment updates','Push only','On')}${R('gift','Rewards & offers','Weekly summary','Weekly')}${R('heart','Health reminders','Push + WhatsApp','On')}`],
['support','Help & support','Fast human assistance.','profile',`<div class="searchbox">${I('search')} Search help</div>${C('24×7 priority support','Gold response target: under 2 minutes.','tint')}${B('Start secure chat')}<button class="flow-btn secondary">Request callback</button>${R('help','Frequently asked questions','Payments, KYC, points and claims')}${R('doc','Raise a grievance','Trackable resolution')}`]
];
const gallery=document.querySelector('#gallery'),home=gallery.querySelector('[data-screen="home"]'),profile=gallery.querySelector('[data-screen="profile"]');
const T=(s,n)=>`<article class="mock flow-screen" data-screen="${s[0]}" data-parent="${s[3]||''}"><div class="phone"><div class="screen"><div class="island"></div><div class="status"><span>9:41</span><span>● ● ▰</span></div><div class="content">${s[4]}</div>${s[3]?'<div class="nav"></div>':''}</div></div><div class="caption"><b>${String(n).padStart(2,'0')} · ${s[1]}</b><small>${s[2]}</small></div></article>`;
home.insertAdjacentHTML('beforebegin',screens.slice(0,8).map((s,i)=>T(s,i+1)).join(''));profile.insertAdjacentHTML('afterend',screens.slice(8).map((s,i)=>T(s,i+14)).join(''));
const navs=[['home','Home','home'],['brief','Services','search'],['gift','Rewards','gift'],['heart','Beneficiary Offers','tag'],['more','More','user']];document.querySelectorAll('.flow-screen .nav').forEach(n=>{const m=n.closest('.mock'),cur=m.dataset.parent;n.innerHTML=navs.map(([icon,label,target])=>`<button type="button" data-go="${target}" class="${target===cur?'active':''}" aria-label="${label}" title="${label}"><span class="ico" aria-hidden="true">${I(icon)}</span></button>`).join('')});
const serviceRoutes=['invest','insurance','health','farms','it','search','search','search'];document.querySelectorAll('[data-screen="home"] .service').forEach((el,i)=>{el.dataset.go=serviceRoutes[i]||'search';el.setAttribute('role','button');el.tabIndex=0});
document.addEventListener('click',e=>{const x=e.target.closest('[data-go]');if(!x||!x.dataset.go)return;e.preventDefault();const t=document.querySelector(`[data-screen="${x.dataset.go}"]`);if(t){document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.go===x.dataset.go));t.scrollIntoView({behavior:'smooth',inline:'nearest',block:'start'})}});
})();
